### PR TITLE
Support for Brazilian holidays

### PR DESCRIPTION
**Pull request by fcrespo82**
I need to provide unit test coverage for this, but I opened the PR already to keep track of it!

Thanks for the module!

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Thank you very much.. I'll be merging your work when you're done!
Cheers

**Comment by fcrespo82** [comment]
Hey @dr-prodigy. Just finished unit tests for this PR. Can you check if it needs any other work.

Thank you!

**Comment by dr-prodigy** [comment]
Very good work: I just had to update some documentation, then I merged everything to beta branch (will be released pretty soon).
Thank you very much, cheers!

**Comment by fcrespo82** [comment]
Oh, I forgot about the docs, sorry!

I should thank you for the module it is very helpful.

Glad I could contribute!

**Comment by dr-prodigy** [comment]
Hi,
I usually complete every contribution merge applying those docs small changes, so no worries at all!

Python_holidays grows up and gets better daily mainly due to your contributions.. So I thank you very much for your support and help!

Cheers

**Pull request merged**
