### PR TITLE
Add UAE holidays

### PR DESCRIPTION
**Pull request by marcomasulli**
Hi @dr-prodigy , took a shoot at adding holidays for UAE after reviewing official calendars for the last 5-6 years. Apart from the usual issues with the islamic calendar, the tests proved accurate.

The UAE government also seems to extend public holidays duration arbitrarily by 1 or 2 days depending on the year, this is not something I implemented, would be a best guess situation.

Feel free to let me know if anything with this needs fixing, I hope this can be of help :-)

Cheers

### CODE REVIEW

**Comment by mborsetti** [comment]
Nice work.

A suggestion: you may consider shadowing https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/singapore.py and make it explicitly clear when the holiday returned is estimated vs. an official date.  I don't think `holiday` should return estimates without being explicit about it.

If you have the time you can also load the actual dates for the past decade or so like for the Singapore module.

**Comment by marcomasulli** [comment]
Good point, I will edit and resubmit. I had shadowed Egypt for the holiday pattern similarities, but did not have estimates there. About Singapore - do you have a source I can get the official dates from?

**Comment by mborsetti** [comment]
The actual dates for Singapore I got directly from the website of the
Ministry of Manpower, which is the official source. To memory this is
documented in the code.

I assume the UAE has a similar official source of information.

**Comment by marcomasulli** [comment]
Hi, I added sources and the actual dates since 2017. The only governmental source which I found only has the last holiday dates for 2019 and all 2020; for the other years I had to rely on national newspaper websites, cross checking each holiday (as they are all officially announced/confirmed separately). 

I will be able to add more information about the previous years further on, please let me know if anything needs fixing. 

Cheers!

**Comment by mborsetti** [comment]
Code looks great to me, excellent!

One last bit: you also need to add testing code in [tests.py](https://github.com/dr-prodigy/python-holidays/blob/master/tests.py). Of course this is as easy as just adapting some other country's test code to the UAE holidays. Please ensure that the tests ideally have 100% [coverage](https://github.com/dr-prodigy/python-holidays#coverage) of the code you wrote, and you can run them yourself before pushing as per [here](https://github.com/dr-prodigy/python-holidays#running-tests). 

Tests not only ensure that the new code works, but also that future changes (including changes made by libraries that are being imported) don't cause it to stop working.

P.S. for the record I did not independently validate the dates.

**Comment by marcomasulli** [comment]
Hi, thanks a lot for the comments and guidance - ran flake8 and tests, rewrote a few things to fit lines within 80 chars (apart from source links). Should something still need fixing please let me know. Cheers!

**Comment by mborsetti** [comment]
Thank you!

I have no further comments, it's up to @dr-prodigy

**Comment by dr-prodigy** [comment]
Hey there,
great collaboration work, brilliant! .. thanks a lot to you both! 👍 

Just for the sake of completeness, last things I made:
- moved target branch to "beta"
- made some more code updates to avoid flake8 complaining for lines too long
- had to revert `f'{aaa}'` strings (very elegant and effective, btw) to good old `'{}'.format(aaa)` to preserve Python2 compat

Merged and available in beta.. cheers! :-)

**Pull request merged**
