### PR TITLE
support new convertdate version

### PR DESCRIPTION
**Pull request by giladmaya**
convertdate API changed and broke IsraelHolidays class
This PR solves the integration issues and reported issues #406 #391

### CODE REVIEW

**Comment by fabaff** [comment]
Is also needed to fix the RPM build issue on Fedora. Thanks

**Comment by maxwhosevillage** [comment]
Would love to see this merged. it is stopping me due to dependency conflict with pytz<2020 from convertdate==2.2.0

**Comment by giladmaya** [comment]
@dr-prodigy any estimation of when this PR will be merged?

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest and good work!
Last December I decided to release the last holidays version supporting Python 2.
It took me more than expected to find time to start the new beta 0.10.5.
Time to merge now: thanks again, best 👍

**Pull request merged**
