### PR TITLE
changed Italy holidays to add all provinces' saints

### PR DESCRIPTION
**Pull request by coffeemaker2017**

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi coffeemaker, thanks a lot for your good work!

Unfortunately, Italy's got a quite huge list of saints, not only the ones you found.
I think that, when working on this task, we should come to, if not to 100%, at least a good point of coverage of them.

Check out this (probably not even totally complete!) list:
https://it.wikipedia.org/wiki/Santi_patroni_cattolici_delle_citt%C3%A0_capoluogo_di_provincia_italiane
(some of the dates are not shown directly in the list, but can be found in the relevant details page, eg for L'Aquila, https://it.wikipedia.org/wiki/San_Massimo_d%27Aveia )

This is a task I've got in my to-do-list: could you help me out with it?

NOTE: given the length of the list, I'd strongly suggest to avoid using only "if" statements to do it.

Please let me know, thx
dr-p

**Comment by coffeemaker2017** [comment]
Hello dr-prodigy,

I'll take another look at the issue and try to complete holidays for Italy for all saints today.
You're right about if statements. Other if statements for already implemented holidays based on province in Italy were just if statement and I wanted to keep the code style consistent, but the fact is, that it's not a good idea.
I let you know about the progress or you'll see changes in the pull request later on.

cm2017

**Comment by dr-prodigy** [comment]
No hurry, when you can :)
Thank you another time!

**Comment by dr-prodigy** [comment]
Hi krolmic,
I realized today that we've lost contact on this work of yours (after I inadvertently closed your PR months ago), which I'd like to get back into the project (in the end, even if not 100% complete, there was some useful data added!).
I know a lot of time is passed (right now I can't see your python_holiday fork anymore), but if you could in some way restore your work, I would be sure glad to merge it.
Thanks a lot, cheers!

**Comment by krolmic** [comment]
Hi dr-prodigy,

first of all, I'm sorry that I didn't finish my work on the PR.
A lot of other things distracted me from finishing it. I cleaned up my github profile recently and I thought my work on python_holiday isn't useful and up-to-date anymore.

I'm going to see what I can do and write you a message.

Best regards
Michael

**Comment by dr-prodigy** [comment]
Hi Michael,
well it's been my fault, I'm sorry.. thank you very much for anything
you'll do!

Tchuss
Maurizio

Il giorno ven 19 ott 2018 alle ore 01:30 Michael Krol <
notifications@github.com> ha scritto:

**Comment by krolmic** [comment]
Ciao Maurizio,

I created a pull request containing all provinces in Italy and their holidays, which are partly missing.
I listed which holidays are missing in a comment in holidays.py.

Best regards
Michael

**Pull request closed without merging**
