### PR TITLE
Add UK Holiday for Queen Elizabeth II Funeral

### PR DESCRIPTION
**Pull request by JPunter**

### CODE REVIEW

**Comment by violuke** [comment]
@dr-prodigy this holiday is in 6 days (and has only just been announced), can this please be merged ASAP? Thank you.

https://www.gov.uk/government/news/bank-holiday-announced-for-her-majesty-queen-elizabeth-iis-state-funeral-on-monday-19-september

**Comment by dr-prodigy** [comment]
Hi @violuke thx for your contribution!
I'm currently working to merge this PR.
Unfortunately, due to our standard release workflow, we can't receive it as a direct hot-fix towards main (master) branch (which would not trigger a new PyPi library version anyway).
We are then merging it on beta branch: please refer to here
https://github.com/dr-prodigy/python-holidays#beta-version
for instructions on how to add a temporary dependency to it. 
Regarding an official release, at the moment we can't guarantee it in the required time, but we will do our best.

Please let me know if this sorts your need out, thx!

**Comment by JPunter** [comment]
Hey @dr-prodigy, 
Thanks for merging the PR. I appreciate the quick turnaround and thank you for the heads up that you can't guarantee the release will occur prior to Monday. We rely on this package for a production payment system so I will have to create a catch directly in our system for this. 
Thanks for your continued work on this package, it's super useful!

**Comment by violuke** [comment]
Thanks also to @JPunter

**Comment by dr-prodigy** [comment]
Of course, thank you very much @JPunter, sorry for not mentioning you before.. KUTGW!

**Comment by dr-prodigy** [comment]
Hi @violuke @JPunter
as you may have noticed, we have just released v.0.16, which includes, along with your PR, all the up-to-now-known holidays regarding Queen Elizabeth mourning across the world: it's been quite a tough work, but we did it :-)
I hope it will be a beneficial for your objectives and needs: I kindly ask you to keep on reporting any inconsistencies you may find, and we will do our best to address them at once.
Best regards
dr-p

**Comment by violuke** [comment]
Thank you, that's very much appreciated 😄

**Pull request merged**
