### PR TITLE
Created bangladesh.py

### PR DESCRIPTION
**Pull request by tasnimislam**
Currently the national holidays have been listed. Soon then Religious holidays will be updated!
python holidays

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi,
thanks again for your interest and work on python-holidays!
Would you please try to add test coverage to your new code?
Tasks required to pass code compliance checks (PEP8) and test coverage are explained in the README.rst file (please refer to beta branch version: there's been a recent update by me).
Please let me know thank you very much!
dr-p

**Comment by tasnimislam** [comment]
Hello,
Sorry for my ignorance. I will reach to you after I complte the tasks.

**Comment by dr-prodigy** [comment]
Hey, no problem, really!
I added these notes - as I always do - not to criticize your good work, but instead just to try suggesting you how to contribute in the best way (I must admit it's not always easy to get into this project taking care of all its requirements).

And of course, feel free to reach out to me to ask for any clarification. I'll be glad to help you.
Thanks again, cheers!
dr-p

**Comment by dr-prodigy** [comment]
Hi @tasnimislam 
any news on this topic?
Thank you very much, KUTGW!
dr-p

**Comment by dr-prodigy** [comment]
Hi Tasnim,
sorry but I can't seem to find any change in your pull request. Have you committed + pushed your new work?
Thank you!

**Comment by tasnimislam** [comment]
I just re-uploaded the file, you can see the test file run results, I have
attached the cmd window with this

**Comment by dr-prodigy** [comment]
Hi, 
I guess you still need to merge the last commit I made to include a US fix lately requested for pulling (which in fact was lacking proper a tests.py review).

Please sync with all the last changes, and you should get tests working again.

From there on, you should be able to add your own tests to cover all your code (I usually aim to 100% coverage: coverage command helps you know which lines are not yet being tested).

Finally, please check your coverage call (tests.py itself shouldn't normally be checked for coverage :) ). Please refer to here for the right one:
https://github.com/dr-prodigy/python-holidays/tree/beta#coverage

Please let me know, thank you!

**Comment by FayzulSaimun** [comment]
@tasnimislam did you upload bangladesh holidays?
any news?

**Comment by dr-prodigy** [comment]
Hi, 
code reviews applied, added tests, CHANGES, README.rst and merged in beta.
Closing,  thx

**Pull request merged**
