### PR TITLE
Starting 2019 CANADA BC Family Day will be 3rd Monday of Feb

### PR DESCRIPTION
**Pull request by goodfore**

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Thank you very much for your contribution.
Please fix Travis CI errors in order to have your PR merged.
Thx
dr-p

**Comment by goodfore** [comment]
Hi dr-prodigy,

I don't quite understand the errors on my second commit. 

"File "tests.py", line 440, in test_family_day
    self.assertNotIn(dt, bc_holidays)
AssertionError: datetime.date(2019, 2, 18) unexpectedly found in {datetime.date(2006, 7, 1): 'Canada Day', datetime.date(2000, 12, 26):......

Any ideas?
Thanks.

**Comment by goodfore** [comment]
Nvm, the test.py needs to be updated. New to GitHub, will try to see if how do I do that.

**Comment by goodfore** [comment]
Ok, I think this build will work. Sorry that I bombard your CI with minor changes; I don't have the IDE setup where I am now.

Thanks,
Joe

**Comment by dr-prodigy** [comment]
Thank you! 👍

**Pull request merged**
