### PR TITLE
Add Support for Chile Holidays

### PR DESCRIPTION
**Pull request by matisaul**
Hi, this is my first contribution of this great solution.

Please tell me if I do something wrong.

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your interest and contribution in the prj!
Your code is well written (very good), but I would kindly ask you, if possible, to provide complete test coverage too, so we stick to 100%.
You can always check this on your local with commands like
$ coverage run --omit=*site-packages* tests.py
$ coverage report
Thanks again, KUTGW

**Comment by dr-prodigy** [comment]
@matisaul : hi any news on this PR? 
In order to merge it, I had to move it to beta branch (branch designated for including new features and bugfixes), and this introduced a conflict. 
Please let me know, thank you very much

**Comment by dr-prodigy** [comment]
Any news?
Thank you very much
dr-p

**Comment by matisaul** [comment]
Hi! Sorry about the long delay...

I made what you suggest me:

$ coverage run --omit=site-packages tests.py
$ coverage report

and return this:

```
 / coverage run --omit=site-packages test.py
 / coverage report
Name       Stmts   Miss  Cover
------------------------------
/test.py    2495   2248    10%

```

I really don't know what that means...

**Comment by dr-prodigy** [comment]
Hi.. Well it means that you haven't implemented sufficient unit tests for your new code (see tests.py);  your tests should check and cover all new code you have added to the project (ie: each line of application code should be executed during the automated tests), and all the test assertions should evaluate to true, in order to maintain 100% of code test coverage.
The same check is done after each commit by Coveralls, and must be passed for the commit to be validated.

**Comment by rpanai** [comment]
I'm trying to work on this.

**Comment by jpsiegel** [comment]
I would appreciate the inclusion of chile hoildays very much, I hope this is ready soon!

**Comment by rpanai** [comment]
@jpsiegel Apparently this PR had some problems I already made another one which was merged see [PR](https://github.com/dr-prodigy/python-holidays/pull/236)

**Comment by rpanai** [comment]
@dr-prodigy you should consider closing this.

**Comment by dr-prodigy** [comment]
Oh yes you're perfectly right! Thank you for pointing this out ;-)

**Pull request closed without merging**
