### PR TITLE
fix German holidays

### PR DESCRIPTION
**Pull request by vlt**
In #110 a problem with the German public Easter and Pentecost holidays was introduced.

### CODE REVIEW

**Comment by Achimh3011** [comment]
No, the problem was fixed. What gives you the idea that Easter and Pentecost are not holidays in entire Germany?

**Comment by vlt** [comment]
> I'd still suggest to keep them as holidays for the entire
> Germany.

You might suggest that to the legislators ;-)
Currently only in the "BB" province these are public
holidays and -- by law -- paid as such, for example.

> Regarding the Reformationstag, you can see the full list
> at https://www.ferienwiki.de/feiertage/reformationstag -
> so the current list is not long enough.

I don't see which region would be missing. Can you specify
that?

**Comment by vlt** [comment]
I moved the "Reformationstag" issue to a separate PR #150.

**Comment by Achimh3011** [comment]
Well, Sundays are paid the same as Holidays, that's why they are not listed in the other federal states. So in terms of workday/free day it does not make a difference. I'm still wondering why there is an explicit definition only in this one state.

If you are looking for holidays to be generated (so some kind of calendaring), it does make a difference. Maybe a differentiation is needed?

**Comment by dr-prodigy** [comment]
Hi, 
thank you both for your contribution.
Unfortunately, I don't read german and have no specific knowledge about holiday laws in DE provinces, so I can't really choose which point of view is best (still, at first thought, I would agree with @Achimh3011 that a Sunday can be considered holiday anytime with no particular harm :) ).
@vlt : given that there is no practical difference on salaries or work contracts (or so Achimh says), why is RS excluded explicitly from holidays in some provinces (or, the largest part of them)? If you could explain this, I'd surely consider to merge your PR (which btw is technically 100% flawless).
Thanks again to both.

**Comment by Achimh3011** [comment]
I dug up an article on this weirdness: if you are forced to work on Pentecoast Sunday you will get normal Sunday premium (50%) where as on Pentecoast Monday you will get the Holiday premium (125%). Easter should be the same, but is not mentioned in the article.

> Wo ist er gesetzlicher Feiertag?
> 
> Einzig das Bundesland Brandenburg macht eine Ausnahme: Hier gilt der Pfingstsonntag als gesetzlich anerkannter Feiertag. Das wirkt sich in diesem Fall tatsächlich aber kaum aus, da Sonntage gesetzlich ohnehin mit Feiertagen gleichgestellt sind.
> 
> Einen wichtigen Unterschied gibt es allerdings: Müssen Sie am Pfingstsonntag arbeiten, bekommen Sie laut eines Urteils des Bundesarbeitsgerichts aus dem Jahre 2011 keinen sogenannten steuerfreien Feiertagszuschlag – es sei denn, Sie arbeiten in Brandenburg. Der Zuschlag beträgt dann 125 Prozent. Der normale Sonntagszuschlag liegt dagegen nur bei 50 Prozent.

https://www.t-online.de/leben/familie/id_69224230/warum-der-pfingstsonntag-kein-gesetzlicher-feiertag-ist.html

**Comment by dr-prodigy** [comment]
Merged.. thx to both! 👍

**Pull request merged**
