### PR TITLE
Introduce subdivision holidays methods

### PR DESCRIPTION
**Pull request by arkid15r**
## Proposed change

Streamline subdivision code handling and improve readability.
Portugal: use holiday groups, split subdivision holidays.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [x] Existing code/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency upgrade (version update)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good (`make pre-commit`)
- [x] I've added tests to verify that the new code works and all tests pass locally (`make test`, `make tox`)
- [x] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Review by KJhellico — COMMENTED** [review]
LGTM. It's an interesting idea 👍

**Comment by arkid15r** [comment]
> LGTM. It's an interesting idea 👍

Thank, I hope it'll open another door to a better structured code.

**Comment by mborsetti** [comment]
I just saw this PR, and want to raise the issue that it _may_ (actually, most likely) be incompatible with the rearchitecting work in the `Improve library loading time by ~3.5x` PR #1049

**Comment by arkid15r** [comment]
> I just saw this PR, and want to raise the issue that as is, it _may_ (actually, most likely) be incompatible with the rearchitecting work in the `Improve library loading time by ~3.5x` PR #1049
> 
> Incorporating it into the new architecture will require some additional work.

I don't see a clear reason for that yet (as I didn't have a chance to look into the PR) but I trust your judgement here Mike. 
I wouldn't worry about this for now as #1049 is still an early stage draft.

Thanks for the heads up!

**Pull request merged**
