### PR TITLE
Add coverage tests for many countries

### PR DESCRIPTION
**Pull request by akosfurton**
Add many other country tests to fix edge cases and improve coverage

@dr-prodigy , please approve the workflows

### CODE REVIEW

**Comment by akosfurton** [comment]
Add many other country tests to fix edge cases and improve coverage

**Review by dr-prodigy — COMMENTED** [review]
Hi @akosfurton !
While I agree on a good number of these reviews, I don't understand why there are a lot of "elif" blocks being replaced by "if".. which is maybe not functionally harmful, but surely less ideal in terms of performance..
could you please explain their reason why and/or review them?
thx!

**Comment by dr-prodigy** [comment]
PS: btw @akosfurton , relevant build tests are also failing (most probably due to some mis-formatting): could you double-check those too?
Thx! 👍

**Comment by akosfurton** [comment]
Yes, will make the above changes and re-run the tests

**Comment by dr-prodigy** [comment]
hey there @akosfurton any news on what above?
thank you very much, KUTGW 👍

**Comment by dr-prodigy** [comment]
At last, I applied this PR too, after some final fixes. Now available in beta, thx 👍

**Pull request merged**
