### PR TITLE
Ukraine holidays

### PR DESCRIPTION
**Pull request by Anian-igor**

### CODE REVIEW

**Comment by Anian-igor** [comment]
I'm so sorry. I don't understand why coverage show me an error.

**Comment by dr-prodigy** [comment]
Hi, thank you for your contribution.

Some notes:
1) To have it pulled & merged, it's mandatory to reach unit test coverage for 100% of the code.

2) Also, in order to avoid notification spamming to project contributors (20 emails in the last 12 hours..), I would also kindly ask you to avoid reiterated pushes for very small changes. Better to write code and unit tests, check everything locally, then commit and push.

Thank you very much for your collaboration, keep up the good work

**Comment by Anian-igor** [comment]
Hello. I'm new for Python. Could you please help me to fix coverage test? I don't understand that test utility want. 
Thanks.

**Comment by dr-prodigy** [comment]
Hi, all needed requirements and commands are available into **.travis.yml** and **README.rst** .

Thank you

**Pull request closed without merging**
