### PR TITLE
Fixed Canada Holiday Calendar

### PR DESCRIPTION
**Pull request by justinasfour04**
The Canada holiday calendar was throwing errors because province was by default None

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Thank you very much! 👍

**Comment by justinasfour04** [comment]
👍 no problem. Great library

**Comment by justinasfour04** [comment]
My changes are gone @dr-prodigy

**Comment by justinasfour04** [comment]
https://travis-ci.org/dr-prodigy/python-holidays/builds/460452003?utm_source=github_status&utm_medium=notification the merge seems to have failed

**Comment by dr-prodigy** [comment]
Sorry they got lost in merging.. Don't know why! 
It should be okay now, please let me know @justinasfour04 thank you!

**Comment by justinasfour04** [comment]
@dr-prodigy When is beta going to be merged into master?

**Comment by dr-prodigy** [comment]
Hi Justin,
I usually don't follow a strict scheduling for pypi releases (which is when
beta branch is merged into master).. I only wait to collect a reasonable
number of new features and bugfixes  and then release a new version. I
currently would say we're pretty there with a 0.9.9.

Anyway, if you need or feel like staying "on the bleeding edge", no
problem: whenever I release a beta version, I always try to commit clean
and tested code, and possibly provide 100% test coverage too.
So whenever you want to update holidays to the latest beta version in your
venv / system, you can just run the command

$ pip install --upgrade
https://github.com/dr-prodigy/python-holidays/tarball/beta

(described here:
https://github.com/dr-prodigy/python-holidays#development-version )

Please let me know your observations.. thank you very much for your
interest and contribution to python-holidays.
Cheers!
dr-p

Il giorno mer 28 nov 2018 alle ore 17:07 Justin Asfour <
notifications@github.com> ha scritto:

**Pull request merged**
