### PR TITLE
Added all italian provinces

### PR DESCRIPTION
**Pull request by energywave**
I've added all italian provinces "santo patrono", wrote in comments the reference links about the dates and the list.
Implemented 100% of the tests about provinces and cities of composites provinces (like Balretta-Andria-Trani).
Edited provinces list in the readme to reflect all the provinces implemented.

### CODE REVIEW

**Comment by energywave** [comment]
I hope to have not made mistakes as this is my first PR...

**Comment by energywave** [comment]
I forgot to say that I didn't add the note in the readme.rst file about "Santo Patrono" of provinces (now called subdivisions) are only valid in "Capoluogo di provincia" and not in the rest of province territory, if not in some exceptions. Just to ensure an informed use of library by users.

**Comment by energywave** [comment]
@dr-prodigy can you please suggest me what's the problem with the quality assurance checks? So the next time I can do what I did not this time.

**Comment by dr-prodigy** [comment]
Hi @energywave 
thank you for your work!
I've just merged it on beta (just a few code format fixes were required.. good job!).
Regarding README notes, I considered not to explicit this: all around the lib (and world too) there are a good number of specific caveats/not obvious behaviours, but none of them appears in the README (aiming to stay short and synthetic). 
Those are usually clarified in the code with comments.
Thx again, best 👍

**Comment by energywave** [comment]
Wonderful, all clear. Thank you and keep on the good work :)

**Pull request merged**
