### PR TITLE
Malaysian holidays

### PR DESCRIPTION
**Pull request by mborsetti**
I've finally finished this.  It was a ton of work, but holidays for all 16 States made into it and they should work on a going forward basis.

Also wrote a very extensive 2021 test suite with a matrix of 768 cells, which I will replicate for 2022 once those dates are available and if required fix any remaining issues with the code.

EDITED TO ADD:
Includes #523 which I messed up in pushing:
- Refactored Chinese lunisolar calendar calculation into the new `LuniSolar` class shared in utils.py. This lengthy code was duplicated in Hong Kong (where it originates from before I copied it), Singapore, and now Malaysia.
- Used the new `LuniSolar` class for China holidays (instead of some Korean(!) library)
- Renamed the shared function `get_gre_date)` (the original name I gave it) to `islamic_to_gre`, which is less confusing as we are now dealing with multiple calendars in utils.py.
- Renamed `isLeapYear` function in HongKong to the Pythonic `is_leap_year`
- A few docstring updates here and there

### CODE REVIEW

**Comment by mborsetti** [comment]
Fixed original failure of test by running pre-commit (for some reason git doesn't do it automatically for this project before pushing).  The tests now is failing for some unrelated Coverall issue, but the code does pass all local tox tests.

**Comment by mborsetti** [comment]
Sorry for dribbling new commits. The weekend is over so this will be the very last one and feel free to incorporate into beta.

Two final improvements:

1. I realized that Wesak day is calculated slightly differently in Malaysia than it is in Singapore (as Vesak day), and implemented this.  These calendars are nothing if convoluted, but fascinating.
2. I fixed all the docstrings so they now work beautifully in IDEs to make life simpler for developers (PyCharm below).  The base class `HolidayBase` and the countries Malaysia and Singapore have useful docstrings, as do all the helper functions in ``utils.py``.
Screenshot 2021-09-20 100804
(of course I only now notice that there's a typo in the very first word of the shiny brand new Malaysia docstring depicted above, sigh; it will be for the next cleanup!). 

Back to other work now; feel free to incorporate into beta.  Ciao!

**Comment by dr-prodigy** [comment]
Hey there Mike @mborsetti !
Thx a lot for your huge work.. it took me a while to check/merge to be honest, but in the end I didn't touch a byte!

..Great work as usual! this is the last commit before releasing.. time for 0.11.3 :)
Cheers 👍

**Comment by mborsetti** [comment]
Maurizio sorry for bungling the separate refactoring pull request; Git is still an untamed beast to me and by the time I realized what I did wrong it was too late.   I made it harder on you to review, and thanks for slogging through it.

**Comment by dr-prodigy** [comment]
Hey Mike that's no problem! Thanks for your work! 👍

**Pull request merged**
