### PR TITLE
Optimize Malaysia observed holidays

### PR DESCRIPTION
**Pull request by KJhellico**

### CODE REVIEW

**Review by arkid15r — COMMENTED** [review]
Just the same naming comments as in `AZ` PR. 

The holidays observation rules code drives me crazy sometimes 🤪.
The tests look much readable now, thank you!

**Comment by KJhellico** [comment]
> Just the same naming comments as in `AZ` PR.

Done.

> The holidays observation rules code drives me crazy sometimes 🤪. The tests look much readable now, thank you!

First, I rewrote the entire code without cycle at the end (as for Kazakhstan, with exceptions for individual years for each holiday).  It looked **really** crazy. :)

**Comment by arkid15r** [comment]
> First, I rewrote the entire code without cycle at the end (as for Kazakhstan, with exceptions for individual years for each holiday). It looked **really** crazy. :)

I know, I viewed the diff :)

**Review by arkid15r — COMMENTED** [review]
👍 LGTM

**Comment by KJhellico** [comment]
> I know, I viewed the diff :)

Look at [this](https://github.com/KJhellico/python-holidays/commit/5c41d114b2ee4520eec923180cec0f9e3125ad19) ;)

**Pull request merged**
