### PR TITLE
Added the official holidays of Aruba

### PR DESCRIPTION
**Pull request by orson1282**
Edit: Full disclosure: I'm a complete noob developer. :smiley:

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Very well done.. thank you very much!

**Comment by orson1282** [comment]
Awesome. Thank you very much too!

**Comment by orson1282** [comment]
Will it be in the 0.9.11 release? ...and about when might that be released?

**Comment by dr-prodigy** [comment]
Of course it will be! No plans for its release yet (but possibly quite soon, given we already have a reasonable number of updates).
If in a hurry, please remember that you can always import beta version as a requirement running this command:
https://github.com/dr-prodigy/python-holidays#development-version 

Cheers!

**Comment by orson1282** [comment]
Cool. Thanks!

**Pull request merged**
