### PR TITLE
Feature/angola long weekend legislation

### PR DESCRIPTION
**Pull request by pietervdw115**
From 2018 if a public holiday fell on a Tuesday or Thursday the Monday or Friday is also a public holiday.

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi,
sorry but, although apparently not highlighted by GH, it seems this PR fails in a unit test (2/1/2017).
Would you please double-check?
Thx, cheers

**Comment by pietervdw115** [comment]
Hi @dr-prodigy,
I am unable to replicate the unit test failing and can also not find anything wrong. That date is specifically chosen as new years falls on the Sunday and therefore is moved to the Monday.
image

**Comment by dr-prodigy** [comment]
Hi @pietervdw115 ,
unfortunately, I've just tested again with same result:
```
======================================================================
FAIL: test_new_years (__main__.TestAngola)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 6726, in test_new_years
    self.assertIn('2017-01-02', self.holidays)  # sunday
AssertionError: '2017-01-02' not found in {datetime.date(1975, 1, 1): "New Year's Day", datetime.date(1975, 3, 28): 'Good Friday', datetime.date(1975, 2, 11): 'Carnival', datetime.date(1975, 2, 4): 'Liberation Day', datetime.date(1975, 3, 8): "International Woman's Day", datetime.date(1975, 4, 4): 'Peace Day', datetime.date(1975, 5, 1): 'Labour Day', datetime.date(1975, 9, 17): "National Heroes' Day", datetime.date(1975, 11, 2): "All Souls' Day", datetime.date(1975, 11, 11): 'Independence Day', datetime.date(1975, 12, 25): 'Christmas Day', datetime.date(2017, 1, 1): "New Year's Day", datetime.date(2017, 4, 14): 'Good Friday', datetime.date(2017, 2, 28): 'Carnival', datetime.date(2017, 2, 4): 'Liberation Day', datetime.date(2017, 3, 8): "Internat [...]
```

Please check you're synced with beta branch and let me know, thx

**Comment by dr-prodigy** [comment]
Hi @pietervdw115,
unfortunately I've just tested again with same result:
```
======================================================================
FAIL: test_new_years (__main__.TestAngola)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 6744, in test_new_years
    self.assertIn('2017-01-02', self.holidays)  # sunday
AssertionError: '2017-01-02' not found in {datetime.date(1975, 1, 1): "New Year's Day", datetime.date(1975, 3, 28): 'Good Friday', datetime.date(1975, 2, 11): 'Carnival', datetime.date(1975, 2, 4): 'Liberation Day', datetime.date(1975, 3, 8): "International Woman's Day", datetime.date(1975, 4, 4): 'Peace Day', datetime.
[...]
```

Would you please double-check you're synced with beta perhaps?
Pls let me know, thx

**Comment by pietervdw115** [comment]
Hi @dr-prodigy, 
The issue has been resolved, branches were not synced up properly :)

**Comment by dr-prodigy** [comment]
Hi, had to merge conflicts and fix some tests for Angola saved into Malawi's.
NP, done in beta.
Thank you, cheers

**Pull request closed without merging**
