### PR TITLE
Add Malaysian holidays

### PR DESCRIPTION
**Pull request by jusce17**
The following holidays still need to be added 

- Isra and Miraj in Malaysia
- NUZUL AL-QUARAN DAY
- The Sultan of Pahang Hol in Pahang
- Birthday of SPB Yang di Pertuan Agong
- Birthday of the Sultan of Kedah in Kedah
- Birthday of the Raja of Perlis
- Hijri New Year Awal Muharram or Maal Hijrah
- The Sultan of Johor Hol
- Muhammad's Birthday

The following holidays are hardcoded and must be changed 
- Thaipusam Holiday

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Great.. thank you very much! 👍

**Comment by mborsetti** [comment]
@jusce17 I'll have a review of the code plus the TODOs soon; most of the work is done, I just need to finish it up and make sure I didn't mess up anything (well, anything obvious).

@dr-prodigy This one isn't done -- as per the original post, it's not ready for primetime.  Not sure if you can reopen.

**Comment by mborsetti** [comment]
Ciao Maurizio,
Ooops ... forgot all about this. Will see if I have time this weekend to work on it; nothing lost by merging it (other that the holidays are incorrect, so not great from a QA workflow perspective) and will fish it out from there and proceed.

**Comment by mborsetti** [comment]
One more thing: I was waiting for #498 to be merged as to make development easier an make the new work compatible with it, but I see it isn't merged and that there are no comments as to why. Any way to can look into it and preferably merge it? I will wait for it before working on fixing Malaysian holidays.

**Pull request merged**
