### PR TITLE
Cleanup Windows-based false positive errors

### PR DESCRIPTION
**Pull request by PPsyrius**
## Proposed change

This cleanup false positive errors for running `pre-commit` checks on Windows-based systems for the following nations:
- **Costa Rica** (`CR`)
- **France** (`FR`)
- **Moldova** (`MD`)
- **Romania** (`RO`)

I'm not sure why this causes loads of errors either, but `make l10n` appears to fix this for me (along with #1067).
Without the change in this PR, running `make pre-commit` would result in the following errors:
```java
====================================================== FAILURES =======================================================
____________________________________________ TestCostaRica.test_l10n_en_us ____________________________________________

self = <tests.countries.test_costa_rica.TestCostaRica testMethod=test_l10n_en_us>

    def test_l10n_en_us(self):
        en_us = "en_US"

        cr = CostaRica(language=en_us)
>       self.assertEqual(cr["2022-01-01"], "New Year's Day")
E       AssertionError: 'Año Nuevo' != "New Year's Day"
E       - Año Nuevo
E       + New Year's Day

tests\countries\test_costa_rica.py:300: AssertionError
_____________________________________________ TestCostaRica.test_l10n_uk ______________________________________________

self = <tests.countries.test_costa_rica.TestCostaRica testMethod=test_l10n_uk>

    def test_l10n_uk(self):
        uk = "uk"

        cr = CostaRica(language=uk)
>       self.assertEqual(cr["2022-01-01"], "Новий рік")
E       AssertionError: 'Año Nuevo' != 'Новий рік'
E       - Año Nuevo
E       + Новий рік

tests\countries\test_costa_rica.py:313: AssertionError
_____________________________________________ TestFrance.test_l10n_en_us ______________________________________________

self = <tests.countries.test_france.TestFrance testMethod=test_l10n_en_us>

    def test_l10n_en_us(self):
        en_us = "en_US"

        fr = France(language=en_us)
>       self.assertEqual(fr["2022-01-01"], "New Year's Day")
E       AssertionError: "Jour de l'an" != "New Year's Day"
E       - Jour de l'an
E       + New Year's Day

tests\countries\test_france.py:179: AssertionError
_______________________________________________ TestFrance.test_l10n_uk _______________________________________________

self = <tests.countries.test_france.TestFrance testMethod=test_l10n_uk>

    def test_l10n_uk(self):
        uk = "uk"

        fr = France(language=uk)
>       self.assertEqual(fr["2022-01-01"], "Новий рік")
E       AssertionError: "Jour de l'an" != 'Новий рік'
E       - Jour de l'an
E       + Новий рік

tests\countries\test_france.py:192: AssertionError
_____________________________________________ TestMoldova.test_l10n_en_us _____________________________________________

self = <tests.countries.test_moldova.TestMoldova testMethod=test_l10n_en_us>

    def test_l10n_en_us(self):
        en_us = "en_US"

        md = Moldova(language=en_us)
>       self.assertEqual(md["2022-01-01"], "New Year's Day")
E       AssertionError: 'Anul Nou' != "New Year's Day"
E       - Anul Nou
E       + New Year's Day

tests\countries\test_moldova.py:111: AssertionError
______________________________________________ TestMoldova.test_l10n_uk _______________________________________________

self = <tests.countries.test_moldova.TestMoldova testMethod=test_l10n_uk>

    def test_l10n_uk(self):
        uk = "uk"

        do = Moldova(language=uk)
>       self.assertEqual(do["2022-01-01"], "Новий рік")
E       AssertionError: 'Anul Nou' != 'Новий рік'
E       - Anul Nou
E       + Новий рік

tests\countries\test_moldova.py:124: AssertionError
_____________________________________________ TestRomania.test_l10n_en_us _____________________________________________

self = <tests.countries.test_romania.TestRomania testMethod=test_l10n_en_us>

    def test_l10n_en_us(self):
        en_us = "en_US"

        ro = Romania(language=en_us)
>       self.assertEqual(ro["2022-01-01"], "New Year's Day")
E       AssertionError: 'Anul Nou' != "New Year's Day"
E       - Anul Nou
E       + New Year's Day

tests\countries\test_romania.py:145: AssertionError
______________________________________________ TestRomania.test_l10n_uk _______________________________________________

self = <tests.countries.test_romania.TestRomania testMethod=test_l10n_uk>

    def test_l10n_uk(self):
        uk = "uk"

        ro = Romania(language=uk)
>       self.assertEqual(ro["2022-01-01"], "Новий рік")
E       AssertionError: 'Anul Nou' != 'Новий рік'
E       - Anul Nou
E       + Новий рік

tests\countries\test_romania.py:158: AssertionError
=============================================== short test summary info ===============================================
FAILED tests/countries/test_costa_rica.py::TestCostaRica::test_l10n_en_us - AssertionError: 'Año Nuevo' != "New Year'...
FAILED tests/countries/test_costa_rica.py::TestCostaRica::test_l10n_uk - AssertionError: 'Año Nuevo' != 'Новий рік'
FAILED tests/countries/test_france.py::TestFrance::test_l10n_en_us - AssertionError: "Jour de l'an" != "New Year's Day"
FAILED tests/countries/test_france.py::TestFrance::test_l10n_uk - AssertionError: "Jour de l'an" != 'Новий рік'
FAILED tests/countries/test_moldova.py::TestMoldova::test_l10n_en_us - AssertionError: 'Anul Nou' != "New Year's Day"
FAILED tests/countries/test_moldova.py::TestMoldova::test_l10n_uk - AssertionError: 'Anul Nou' != 'Новий рік'
FAILED tests/countries/test_romania.py::TestRomania::test_l10n_en_us - AssertionError: 'Anul Nou' != "New Year's Day"
FAILED tests/countries/test_romania.py::TestRomania::test_l10n_uk - AssertionError: 'Anul Nou' != 'Новий рік'
```

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency upgrade (version update)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good: `make pre-commit`
- [x] All tests pass locally: `make test`, `make tox` (we strongly encourage adding tests to your code)
- [x] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Comment by PPsyrius** [comment]
The checker suddenly runs fine even without the code above somehow, gonna close this PR down for now unless I can replicate the mentioned error above again

**Comment by arkid15r** [comment]
> I'm not sure why this causes loads of errors either, but `make l10n` appears to fix this for me (along with #1067). Without the change in this PR, running `make pre-commit` would result in the following errors:

`make pre-commit` doesn't run any test. It seems you meant `make check` or `make test`

**Comment by mborsetti** [comment]
Thanks for this PR; I was getting the same errors in Windows when working on PR [Improve library loading time by ~3.5x](https://github.com/dr-prodigy/python-holidays/pull/1049) but didn't have time to chase them down, also because Windows does not have `make` (it's only install-hackable).

**Comment by KJhellico** [comment]
These errors indicate that .mo files were missing (most likely). Running `scripts\generate_mo_files.py` should help.

**Comment by mborsetti** [comment]
> These errors indicate that .mo files for newly localized countries were missing (most likely). Running `scripts\l10n\generate_mo_files.py` should help.

Thanks.  I worked with the code from GitHub and got those errors.  Apologize for the question, but am not (yet) familiar with this l10n methodology: am I supposed to run `scripts\l10n\generate_mo_files.py` after downloading the code from GitHub into my IDE? If so, I cannot find anything about it in the [documentation ](https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst)

**Pull request closed without merging**
