### PR TITLE
Do not expand into other years

### LINKED ISSUE #569: US Holidays Error: dictionary changed during iteration when passing years to holidays.US constructor
Attempting to use code to get US holidays for specific years.  This code works for some countries but not US (nor Canada)

```
import holidays
import numpy as np
print(holidays.__version__)
years = np.array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])
x = holidays.US(years=years)
```

This code works when I try different countries: FR, GB, RU, DE, ES, CZ, AU, JP, CN, IN

This syntax **fails** to return results for the countries: US, CA

This syntax for passing numpy arrays I found in a ticket with a CZ example.  (https://github.com/dr-prodigy/python-holidays/pull/528).

I am running on Databricks runtime 10.0.  The holidays version is 0.11.3.1 as you see below.

The output I got was for US (or CA) is:
```
0.11.3.1
Out[41]: 
RuntimeError: dictionary changed size during iteration
```

Example output when I use another country, such as AU is:
```
0.11.3.1
Out[42]: {datetime.date(2016, 1, 1): "New Year's Day",
 datetime.date(2016, 1, 26): 'Australia Day',
 datetime.date(2016, 3, 25): 'Good Friday',
 datetime.date(2016, 3, 28): 'Easter Monday',
 datetime.date(2016, 4, 25): 'Anzac Day',
 datetime.date(2016, 12, 25): 'Christmas Day',
 datetime.date(2016, 12, 27): 'Christmas Day (Observed)',
 datetime.date(2016, 12, 26): 'Boxing Day',
 datetime.date(2017, 1, 1): "New Year's Day",
 datetime.date(2017, 1, 2): "New Year's Day (Observed)",
...
```

### PR DESCRIPTION
**Pull request by mborsetti**
This fixes #569 by ensuring that only holidays for the year requested are returned, preventing any inadvertent expansion.  This is enforced through a new test (which identifies the offending holiday, if any, for easier debugging). 

As a result quite a few countries had to be fixed as they were not behaving correctly. Of note particular note is Israel as it required extensive modifications as the variable `year`(!) was being overwritten within the function itself(!), and Botswana, which returned a holiday in 2019 at all times.

### CODE REVIEW

**Comment by mborsetti** [comment]
@dr-prodigy Not sure why this one wasn't merged but I made mistakes and inadvertently put two commits in here that don't belong.  Hopefully you can undo them and apply it.

The problem is that expanding (calculating) other years not only break things, but it's contrary to the documentation.

**Comment by dr-prodigy** [comment]
Hi @mborsetti thank you for this great contrib!
I unfortunately noticed relevant tests are failing.
So I tried a manual merge / fix of this PR, but in fact there are a number of issues (mainly regarding classes and method renames in holidays.utils) I would avoid to mess up with (also because there are other PRs waiting for this to be released).
Would you please review this PR to fix the issues?
Thank you very much as usual! :-)

**Comment by dr-prodigy** [comment]
PS: it seems it also requires a conflict fix after releasing #602 (Sphinx doc) .. thx! 👍

**Comment by mborsetti** [comment]
@dr-prodigy Will fix it and make it compatible with #602.

**Comment by mborsetti** [comment]
This time `git merge` worked as expected and everything works (at least locally in `tox`).  Ready to merge.

**Comment by mborsetti** [comment]
This time `git merge` worked as I expected without too much pain and everything works now, at least locally in `tox`. Yay!

Ready to merge.

**Pull request merged**
