### PR TITLE
Add Juneteenth National Holiday

### PR DESCRIPTION
**Pull request by jusce17**

### CODE REVIEW

**Comment by jusce17** [comment]
This commit is based on the issue #488

**Comment by jusce17** [comment]
this commit is based on the issue #482

**Comment by dr-prodigy** [comment]
Thank you very much! 👍

**Comment by nattofriends** [comment]
Looks like this does the same thing as #474?

**Comment by jusce17** [comment]
@nattofriends, I just checked it now and you are right, I've also seen this problem in other countries, I will be making a PR later this week to fix it

**Comment by dr-prodigy** [comment]
Thank you @jusce17 ! 👍

**Pull request merged**
