### PR TITLE
Prophet holidays

### PR DESCRIPTION
**Pull request by tserekh**
Adding Indonesia, Thailand, Philippines and Pakistan
Belarus is already in library.
Based on holidays from Prophet but have many changes because Prophet include not only public holidays.

https://github.com/dr-prodigy/python-holidays/issues/538

### CODE REVIEW

**Comment by tserekh** [comment]
I am confused about computed test coverege. How it should be improved?

**Comment by dr-prodigy** [comment]
Hi @tserekh
thanks for this great work!
You can find details on how to do test and improve coverage here:
https://github.com/dr-prodigy/python-holidays/tree/beta#running-tests-and-coverage

In particular, the second command should help you find out which code is not yet covered.

Cheers!

**Comment by tserekh** [comment]
@dr-prodigy, thank you. I am going to imrpove test coverage

**Comment by tserekh** [comment]
If think test coverege is so low due to hardcoded holidays. It is hardcoded due to dependency of lunar calendar on geographic coordinates. Now I am working on implemention universal lunar calender for any coordinates using https://github.com/brandon-rhodes/pyephem

**Comment by dr-prodigy** [comment]
hi @tserekh could you proceed in your above activity? thx, best 👍

**Comment by arkid15r** [comment]
Continued in https://github.com/dr-prodigy/python-holidays/pull/887

**Pull request closed without merging**
