### PR TITLE
Add support for Korea holidays

### PR DESCRIPTION
**Pull request by 1kko**
Copied from HongKong Holidays for Lunar calculation function.
- Added Tests for each holidays
- Works until 2099.

### CODE REVIEW

**Comment by minsuke** [comment]
정말 감사합니다. 왜 우리나라만 없는가 했는데. 이렇게 직접 만들어주셨네요. 

thx for your workday component code dr-prodigy, I wish Korean workday merge asap. : )

**Comment by dr-prodigy** [comment]
Hi, merged to beta branch. Thank you very much for your support!
dr-p

**Comment by chongdae** [comment]
@1kko @dr-prodigy 
Korean lunar calendar is differ from Chinese one.

Followings are the lists of differences between 1950 and 2050:
Lunar date: 1-1
Korea: 1916-02-04, China: 1916-02-03
Korea: 1944-01-26, China: 1944-01-25
Korea: 1954-02-04, China: 1954-02-03
Korea: 1958-02-19, China: 1958-02-18
Korea: 1966-01-22, China: 1966-01-21
Korea: 1988-02-18, China: 1988-02-17
Korea: 1997-02-08, China: 1997-02-07
Korea: 2027-02-07, China: 2027-02-06
Korea: 2028-01-27, China: 2028-01-26
Lunar date: 4-8
Korea: 1931-05-25, China: 1931-05-24
Korea: 1968-05-05, China: 1968-05-04
Korea: 2001-05-01, China: 2001-04-30
Korea: 2012-05-28, China: 2012-04-28
Korea: 2023-05-27, China: 2023-05-26
Lunar date: 8-15
Korea: 1942-09-25, China: 1942-09-24
Korea: 1978-09-17, China: 1978-09-16
Korea: 2040-09-21, China: 2040-09-20


And this is the script for generating:
`
from korean_lunar_calendar import KoreanLunarCalendar
from lunardate import LunarDate

for (m, d) in [(1, 1), (4, 8), (8, 15)]:
    print('Lunar date: {}-{}'.format(m, d))
    for y in range(1900, 2050):
        calendar = KoreanLunarCalendar()
        calendar.setLunarDate(y, m, d, False)
        d1 = calendar.SolarIsoFormat()

        dd = LunarDate(y, m, d).toSolarDate()
        d2 = dd.strftime('%Y-%m-%d')

        if d1 != d2:
            print ('Korea: {}, China: {}'.format(d1, d2))`

**Comment by 1kko** [comment]
@dr-prodigy Hi, I was wondering if I could import external library in this case. https://github.com/usingsky/korean_lunar_calendar_py/blob/master/korean_lunar_calendar/korean_lunar_calendar.py

Or should I just copy the part of code from the library?
Of course, I would ask for permission in latter case.

**Comment by 1kko** [comment]
@chongdae 
Thank you for your information.

I asked permission to have copy some part of his code from korean_lunar_calendar.
https://github.com/usingsky/korean_lunar_calendar_py/issues/2#issue-582166904

I made update to my repository meanwhile.
https://github.com/1kko/python-holidays

After getting the permission, I'll make push request to beta branch.

**Comment by chongdae** [comment]
@1kko

Exceptioally, alternative holidays are also applied for Children's day in 2025 and 2044.
Buddha's day overlaps with Children's day.
May 6 become holidays in both cases.

**Comment by dr-prodigy** [comment]
Hey there @1kko of course, please go on and add import to that library! Especially because it seems very light and well designed.
I'll surely be glad to merge your work.. thank you very much, cheers!
dr-p

**Comment by 1kko** [comment]
@chongdae Thank you for reporting. I'll try to fix it in next few weeks.

**Comment by 1kko** [comment]
@chongdae I fixed Alternative Children's Day at #300 
https://github.com/dr-prodigy/python-holidays/pull/300/commits/7088375b845de6c3af1dc18d681051bbf4d38ebd

**Pull request merged**
