### PR TITLE
Replace while loops with dateutil logic (#768)

### PR DESCRIPTION
**Pull request by KJhellico**

### CODE REVIEW

**Review by arkid15r — CHANGES_REQUESTED** [review]
This looks good in general and the direction is 100% correct.

However I don't think that current tests cover these cases in a sufficient manner. Could you add related tests for all affected countries and make sure they are green before and after the refactoring? 

It's important to have efficient code but compatibility/reliability takes priority here. I hope you understand my point.

Thank you @KJhellico!

**Comment by KJhellico** [comment]
> It's important to have efficient code but compatibility/reliability takes priority here. I hope you understand my point.

Yes, I noticed that there are not enough tests (there was wrong calculation of Queen's Birthday in South Africa and Defense Forces Day in Zimbabwe). I will try to add more.

**Comment by arkid15r** [comment]
> Yes, I noticed that there are not enough tests (there was wrong calculation of Queen's Birthday in South Africa and Defense Forces Day in Zimbabwe). I will try to add more.

Let me know if you need help with that.

**Comment by KJhellico** [comment]
I found that South Africa observed calculation was incorrect (if holiday fall on a Sunday, only followed Monday should be holiday, not followed workday). Should I change it in this PR or make separate? @arkid15r

**Comment by KJhellico** [comment]
I removed SA from this PR, and added tests for affected holidays in rest of countries

**Review by arkid15r — APPROVED** [review]
It looks like you've fixed Zimbabwe heroes day bug with this refactoring, well done!
Looks good to me!

**Pull request merged**
