### PR TITLE
Adding Venezuela to the list

### PR DESCRIPTION
**Pull request by antusystem**
I add the venezuela.py file, but still don't know how to change the rest of the files for it to load with holidays.py. I use Colombia and Brazil as a guide.

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Thank you very much! 👍 
Cheers
dr-p

**Comment by antusystem** [comment]
Thanks for including it. Any idea when will you add it to the master? and
also, will you update the feedstock for conda-forge at the same time you
update the master branch? Thanks

**Comment by dr-prodigy** [comment]
Hi @antusystem
in general, I honestly don't usually have a clear plan on when releasing a new lib version, so I don't have it now :)
 
My strategy is usually packing a "reasonable" number of tested changes, while keeping the beta branch as the source "bleeding edge" version (always retaining the max degree of compatibility / no bug status whenever possible).
In the main holidays doc (README) you will find out how to update your dependencies using beta as source.

I instead don't collaborate with conda-forge project nor push anything towards it, so sorry to say I can't answer for that!

Hope this helps 👍

**Comment by antusystem** [comment]
Oh, I understand. I will see how to work with beta branch in the README, thanks. 

And don't worry for conda-forge, I will see about it later. Thanks

**Pull request merged**
