### PR TITLE
Add day for NY holidays from government decree

### PR DESCRIPTION
**Pull request by Enzokot**

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi @Enzokot ,
thank you for your support.
Would you please add a specific unit test to cover your new code?
Thx!

**Comment by Enzokot** [comment]
@dr-prodigy Hi! Sorry, may bad.

**Comment by dr-prodigy** [comment]
Hi @Enzokot I ran checks on your code, but they're currently failing: would you please double-check / review?
Thx! 👍

**Comment by Enzokot** [comment]
@dr-prodigy Hi! Sorry, my bad. Done. Please, re-run the test.

**Comment by dr-prodigy** [comment]
Hi @Enzokot,
your PR is merged in beta.. thank you very much for your support! 👍

**Pull request merged**
