### PR TITLE
Add Angolan National Holidays

### PR DESCRIPTION
**Pull request by jusce17**
I have added all the Angolan holidays as well as the Long weekend is defined by the local Government

### CODE REVIEW

**Comment by jusce17** [comment]
It hasn't been added yet, am I supposed to merge on master on the beta branch ?

**Comment by dr-prodigy** [comment]
Hey there @jusce17
thank you very much for your support, and sorry for my delay.
I would kindly ask you to provide proper support for flake8 and coverage, as explained here:
https://github.com/dr-prodigy/python-holidays#running-tests

Thanks again, cheers
dr-p

**Comment by jusce17** [comment]
Thanks for the reply @dr-prodigy 
I am fixing it right now

**Comment by pietervdw115** [comment]
Hi @jusce17,
I have also been working on Angola National Holidays and was not sure about the 'long weekends' that you mentioned. Here are the changes I made to implement this:
https://github.com/dr-prodigy/python-holidays/pull/388

**Comment by jusce17** [comment]
Hi @pietervdw115 , 
awesome, I will just add it up on the work you have done

**Comment by jusce17** [comment]
Also, I saw that many non-english speaking countries have their holidays displayed on their official language. Shall put in portuguese or the rule of thumbs here is to put all in English ?

**Comment by dr-prodigy** [comment]
Hi @jusce17 
although some exceptions are present, I confirm our usual approach is to provide holidays in the local language.

In these days I'm working to prepare the next release: please let me know if you expect to complete your work in some days, so that I can include it in the new version.

Thanks, cheers
dr-p

**Comment by jusce17** [comment]
Hi @dr-prodigy 
I can finish it right away, I just need you to accept the PR [388](https://github.com/dr-prodigy/python-holidays/pull/388) to avoid conflict.

Thanks,
Eden

**Comment by dr-prodigy** [comment]
Hi @jusce17 
unfortunately, I just asked a review on #388 , because it's failing on one test.
I'll wait for the fix (if not requiring too much), then merge it.
Please let some time for this and I'll let you know, thank you!

**Comment by jusce17** [comment]
Hi @dr-prodigy 
If my last commit passes the tests, I think you can merge it

**Comment by jusce17** [comment]
Hi @dr-prodigy you can merge it now, it won't longer conflict with [#388 ](https://github.com/dr-prodigy/python-holidays/pull/388)

**Comment by dr-prodigy** [comment]
Everything fine, merged to beta.. thank you very much! 👍

**Pull request merged**
