### PR TITLE
Add Japanese holidays on the new Emperor

### PR DESCRIPTION
**Pull request by kokinomura**
- Add new holidays regarding the ceremonies of the new Emperor in Japan

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your contribution!

Question about it: I gave a look to your code, and noticed you've provided logic for 2019 only.
To explain my lifecycle principle, I use to say "we aim always to providing a final release library, even if we already know it won't be so".. so isn't there the possibility to manage/support future years too (eg: `if year **>=** 2019:` ) ?
Of course, if something in the future will change, there will be a new release to fix it.. and so on :-)

I rely on you for this because I'm not aware of how holidays in Japan work.. thanks again!

NOTE: I moved the target branch to "beta", which is the branch we use to include new PR.

**Comment by kokinomura** [comment]
The two sections with `if year == 2019` are both related to the change of the Emperor, which is planned to perform this year, and there will no holidays like them from next year. I'm sorry I didn't explain enough with comments, but the latter section, which has two holidays,  is also related to Enthronement Day. These days become holidays only this year.

**Comment by kokinomura** [comment]
Let me also explain some hard-coded functions.

`_add_national_holidays` and `_add_substitute_holidays` can be calculated with programs because they are established based on a series of weekdays and holidays, (a weekday between national holidays becomes a holiday, and a Monday after a national holiday on Sunday becomes a holiday), but the code can be long and these holidays are changed by Government sometimes. This is why I chose to hard code.

**Comment by dr-prodigy** [comment]
Hey no problem at all, I just wanted to double check .. moreover I noticed now there's a `if year >= 2020:` block, so it's my fault, in the end ;-)

..Going to merge, thank you very much again!

**Pull request merged**
