### PR TITLE
Adding Paraguay public holidays support

### PR DESCRIPTION
**Pull request by sfeliu**
Hi, this is my first constribution in a open source library. I have more latin conutries to add, but i want to know if this contribution is okay in order to made the other countries.
Thanks

### CODE REVIEW

**Comment by sfeliu** [comment]
Sorry, I forget to make unit Tests.

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your interest and contribution to the project!
Do you think you'll be able to complete your unit test to keep code coverage at 100%?
Please let me know, thanks in advance.
Cheers

**Comment by dr-prodigy** [comment]
Any news?
Please let me know, thank you very much
dr-p

**Comment by sfeliu** [comment]
Yes I will do it, but I have no time now due to college and work. I hope that I could finish in less than one month. That's okay?

**Comment by dr-prodigy** [comment]
Oh yes of course, that's totally OK.
If in the meantime I'll be able to work on it and complete it on my own, I will surely let you know. 

Thank you very much, cheers

**Comment by rparrapy** [comment]
Any way I can help with this? I really want Paraguay support :)

**Comment by sfeliu** [comment]
> Any way I can help with this? I really want Paraguay support :)

Sorry, i forget it. I don't think i am going to do it  any time soon.
So if you want to continue, or start it over, it's ok. 👍

**Pull request merged**
