### PR TITLE
Added Country INDIA holidays

### PR DESCRIPTION
**Pull request by shauryauppal**
States holidays and all national holidays of India added.

### CODE REVIEW

**Comment by shauryauppal** [comment]
@dr-prodigy Why line number 73 is uncovered. I did not even touch that part of the code. Please help me in this case.

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your work.. very appreciated.

Unfortunately, your new code didn't pass coveralls checks.

This is not due to line 73 (previously already uncovered), but instead on all your new provinces' logic:
https://coveralls.io/builds/18051876/source?filename=holidays.py#L3278
Would you please provide tests for them?

When all checks are okay, I will be merging your code.

Thanks in advance, have a nice day
dr.p

**Comment by shauryauppal** [comment]
@dr-prodigy Solved. Please Merge

**Comment by dr-prodigy** [comment]
I will upload a new library version to PiPy ASAP.
Thank you for your contribution!

**Pull request merged**
