### PR TITLE
Added a missing Holiday to Venezuela

### PR DESCRIPTION
**Pull request by antusystem**
Hi, I missed "Muerte del Libertador Simón Bolívar" when I wrote the holidays for Venezuela, I added them this time

### CODE REVIEW

**Comment by antusystem** [comment]
ok I don't know how to resolve the error: **Tests / Run Quality Assurance (pull_request)**

**Comment by javicalle** [comment]
You can try fix the coverage with:
```
python -m black holidays/countries/venezuela.py
```

Also, you are pointing to the master branch and I believe that all PR must point to `dev` branch

**Comment by antusystem** [comment]
Ohh, let me try that command, though, first time I see it .

I was doing it in the beta branch, but probably change it and didn't realize it

**Comment by dr-prodigy** [comment]
@javicalle
> You can try fix the coverage with:
> 
> ```
> python -m black holidays/countries/venezuela.py
> ```
> 
> Also, you are pointing to the master branch and I believe that all PR must point to `beta` branch

Thank you!
This is substantially correct, although `black` package is not a dev explicit requirement, so a call like that would usually fail.
Please refer to [here](https://github.com/dr-prodigy/python-holidays/tree/beta#ensure-all-staged-files-are-up-to-standard) for the proper instructions.


@antusystem 
> Ohh, let me try that command, though, first time I see it .
> 
> I was doing it in the beta branch, but probably change it and didn't realize it

Not a problem! I switched your PR target to beta.
On the other hand, test coverage for Venezuela is a bit low (87%) so, while still being on it, I kindly ask you to review your tests to reach the [required value](https://github.com/dr-prodigy/python-holidays/tree/beta#contributions).
Please refer to [here](https://github.com/dr-prodigy/python-holidays/tree/beta#running-tests-and-coverage) for detailed commands to do it.
Thank you both, cheers! 👍

**Comment by antusystem** [comment]
Ok done, I downloaded my repo and used pre-commit and pytest to check everything. Thanks for the link provided :)

**Comment by dr-prodigy** [comment]
Hi @antusystem I had to rework your code due to:
- some missing tests
- some mistakes in the "Semana Santa y Carnaval" block

Now it's 100% working and tests covered: released in beta.
Cheers

**Pull request merged**
