### PR TITLE
Update readme file: alphabetically order "prov/state" entries

### LINKED ISSUE #484: Alphabetically order the "prov/state" list in README for all countries.
Currently the following four countries' `prov` lists in the README file are not ordered alphabetically. It will be helpful to have them alphabetically ordered for the users of this library.

- India
- Brazil
- Germany
- NewZealand

```rst
=================== ========= =============================================================
Country             ISO code  Provinces/States Available
=================== ========= =============================================================
Brazil              BR/BRA    state = AC, AL, AP, AM, BA, CE, DF, ES, GO, MA, MT, MS, MG,
                              PA, PB, PE, PI, RJ, RN, RS, RO, RR, SC, SP, SE, TO
Germany             DE/DEU    prov = BW, BY, BYP, BE, BB, HB, HH, HE, MV, NI, NW, RP, SL,
                              SN, ST, SH, TH
India               IN/IND    prov = AS, SK, CG, KA, GJ, BR, RJ, OD, TN, AP, WB, KL, HR,
                              MH, MP, UP, UK, TN
NewZealand          NZ/NZL    prov = NTL, AUK, TKI, HKB, WGN, MBH, NSN, CAN, STC, WTL,
                              OTA, STL, CIT
```

### PR DESCRIPTION
**Pull request by sugatoray**
This closes #484.

- [x] The changes are only in the [README](README.rst) file.

I used a convenience function for sorting, keeping it documented here for quick access.

```python
sortme = lambda p: ', '.join(sorted([str(x) for x in p.split(", ")]))

## For NewZealand
prov = "NTL, AUK, TKI, HKB, WGN, MBH, NSN, CAN, STC, WTL, OTA, STL, CIT"
sortme(prov)
# Output: 'AUK, CAN, CIT, HKB, MBH, NSN, NTL, OTA, STC, STL, TKI, WGN, WTL'
```

### CODE REVIEW

**Comment by sugatoray** [comment]
@dr-prodigy Please take a look at this PR. Hopefully you will be able to merge it swiftly without any more changes. Please let me know your thoughts. Thank you.

**Comment by dr-prodigy** [comment]
Hi @sugatoray thank you for your interest and support.
While the doc review commits are definitely correct and mergeable, I don't think I can merge the last commit regarding conda forge, for its publishing is not backed by our project (so there won't be any guarantee on publishing sync with PyPI and code too).
Therefore I would kindly ask you to undo the last commit so I can merge your PR.
Available for clarifications, thx in advance.
Cheers!

**Comment by sugatoray** [comment]
> Hi @sugatoray thank you for your interest and support.
> While the doc review commits are definitely correct and mergeable, I don't think I can merge the last commit regarding conda forge, for its publishing is not backed by our project (so there won't be any guarantee on publishing sync with PyPI and code too).
> Therefore I would kindly ask you to undo the last commit so I can merge your PR.
> Available for clarifications, thx in advance.
> Cheers!

@dr-prodigy  Thank you, I have rolled back the `conda` related changes.

**Comment by dr-prodigy** [comment]
Thank you! 👍

**Pull request merged**
