### PR TITLE
Ethiopian Holidays

### PR DESCRIPTION
**Pull request by tedtad**
Adding Ethiopian holidays to python-holiday

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi @tedtad
thank you for your effort and support.
I checked your work to merge it, but unfortunately:
- it fails flake8 checks on code formatting
- there are some wrong / failing tests (mainly on Sep 2019)
- test code coverage is quite low (approx 80%)

Would you please fix those issues and push an updated PR?

Thx in advance, best!

**Comment by tedtad** [comment]
Hi @dr-prodigy 

Thanks for your comment and time. But, I can't proceed further since my test have frequently encountered with the following error: Since, I'm novice, please help me fixing it.

The process '/opt/hostedtoolcache/Python/3.10.0/x64/bin/pre-commit' failed with exit code 1

**Comment by dr-prodigy** [comment]
Hi @tedtad 
from my checks, it seems your tests are not correctly asserting your code.

This is the output of your tests run locally:

```
=================================== FAILURES ===================================
____________________________ TestEthiopia.test_2019 ____________________________

self = <test.countries.test_ethiopia.TestEthiopia testMethod=test_2019>

    def test_2019(self):
        self.assertIn(date(2019, 1, 7), self.holidays)
        self.assertIn(date(2019, 1, 19), self.holidays)
        self.assertIn(date(2019, 3, 2), self.holidays)
        self.assertIn(date(2019, 4, 28), self.holidays)
        self.assertIn(date(2019, 4, 26), self.holidays)
        self.assertIn(date(2019, 5, 1), self.holidays)
        self.assertIn(date(2019, 5, 5), self.holidays)
        self.assertIn(date(2019, 5, 28), self.holidays)
>       self.assertIn(date(2019, 9, 12), self.holidays)
E       AssertionError: datetime.date(2019, 9, 12) not found in {datetime.date(2019, 9, 11): 'አዲስ ዓመት እንቁጣጣሽ', datetime.date(2019, 9, 28): 'መስቀል', datetime.date(2019, 1, 7): 'ገና', datetime.date(2019, 1, 19): 'ጥምቀት', datetime.date(2019, 4, 26): 'ስቅለት', datetime.date(2019, 4, 28): 'ፋሲካ', datetime.date(2019, 3, 2): 'አድዋ', datetime.date(2019, 5, 1): 'የሰራተኞች ቀን', datetime.date(2019, 5, 5): 'የአርበኞች ቀን', datetime.date(2019, 5, 28): 'ደርግ የወደቀበት ቀን', datetime.date(2019, 6, 5): 'ኢድ አልፈጥር', datetime.date(2019, 8, 11): 'አረፋ', datetime.date(2019, 11, 9): 'መውሊድ'}

test/countries/test_ethiopia.py:35: AssertionError
_____________________ TestEthiopia.test_ethiopian_newyear ______________________

self = <test.countries.test_ethiopia.TestEthiopia testMethod=test_ethiopian_newyear>

    def test_ethiopian_newyear(self):
>       self.assertIn(date(2019, 9, 12), self.holidays)
E       AssertionError: datetime.date(2019, 9, 12) not found in {datetime.date(2019, 9, 11): 'አዲስ ዓመት እንቁጣጣሽ', datetime.date(2019, 9, 28): 'መስቀል', datetime.date(2019, 1, 7): 'ገና', datetime.date(2019, 1, 19): 'ጥምቀት', datetime.date(2019, 4, 26): 'ስቅለት', datetime.date(2019, 4, 28): 'ፋሲካ', datetime.date(2019, 3, 2): 'አድዋ', datetime.date(2019, 5, 1): 'የሰራተኞች ቀን', datetime.date(2019, 5, 5): 'የአርበኞች ቀን', datetime.date(2019, 5, 28): 'ደርግ የወደቀበት ቀን', datetime.date(2019, 6, 5): 'ኢድ አልፈጥር', datetime.date(2019, 8, 11): 'አረፋ', datetime.date(2019, 11, 9): 'መውሊድ'}

test/countries/test_ethiopia.py:43: AssertionError
________________________ TestEthiopia.test_hijri_based _________________________

self = <test.countries.test_ethiopia.TestEthiopia testMethod=test_hijri_based>

    def test_hijri_based(self):
        if sys.version_info >= (3, 6):
            import importlib.util
    
            if importlib.util.find_spec("hijri_converter"):
                self.holidays = holidays.ET(years=[2019])
                # eid_alfitr
>               self.assertIn(date(2019, 6, 4), self.holidays)
E               AssertionError: datetime.date(2019, 6, 4) not found in {datetime.date(2019, 9, 11): 'አዲስ ዓመት እንቁጣጣሽ', datetime.date(2019, 9, 28): 'መስቀል', datetime.date(2019, 1, 7): 'ገና', datetime.date(2019, 1, 19): 'ጥምቀት', datetime.date(2019, 4, 26): 'ስቅለት', datetime.date(2019, 4, 28): 'ፋሲካ', datetime.date(2019, 3, 2): 'አድዋ', datetime.date(2019, 5, 1): 'የሰራተኞች ቀን', datetime.date(2019, 5, 5): 'የአርበኞች ቀን', datetime.date(2019, 5, 28): 'ደርግ የወደቀበት ቀን', datetime.date(2019, 6, 5): 'ኢድ አልፈጥር', datetime.date(2019, 8, 11): 'አረፋ', datetime.date(2019, 11, 9): 'መውሊድ'}

test/countries/test_ethiopia.py:76: AssertionError

```

You you should fix those errors so that every test is successful.

The commands to run tests on your local are explained here: 
https://github.com/dr-prodigy/python-holidays#running-tests-and-coverage

in short, if you want to run Ethiopian tests only (faster):
`python -m pytest test/countries/test_ethiopia.py
`

I unfortunately can't provide more help than this: my lack in your language and culture doesn't allow me to help you further in any code analysis.

Keep up the good work! 👍

**Comment by tedtad** [comment]
> 

Thank you, I have done as you have suggested.

**Comment by dr-prodigy** [comment]
Hi @tedtad 
thank you.. there still were some reviews required (a few missing tests + a wrong leap year calculation too!). 
Now it's done and the code is "in shape": released in beta.
Note: although I reviewed your code and tests, I took for granted your holiday names & dates.
Cheers 👍

**Comment by tedtad** [comment]
> Hi @tedtad thank you.. there still were some reviews required (a few missing tests + a wrong leap year calculations too!). Now it's done and the code is "in shape": released in beta. Note: although I reviewed your code and tests, I took for granted your holiday names & dates. Cheers 👍

Thank you @dr-prodigy, I'll address those missing tests especially for nonassertion and loops. Regarding, leap year, I intentionally add 1, to consider the Ethiopian case, which has a unique calendar like Coptics'. For your reference, pls check out the Ethiopian calendar of 2019 from [link](https://www.timeanddate.com/calendar/?year=2019&country=81)

**Comment by tedtad** [comment]
> he code is "in shape": released in beta.
> Note: although I re

አመሰግናለሁ / Thanks @dr-prodigy

**Pull request merged**
