### PR TITLE
Add Finnish holidays

### PR DESCRIPTION
**Pull request by Ardetus**

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Hi, your build is failing.
Pls fix and re-issue PR.
Thank you very much
dr.p

**Comment by hugovk** [comment]
That's probably from this morning's Travis CI outage: https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

@dr-prodigy Please can you click the "restart build" button?

**Comment by dr-prodigy** [comment]
Sorry it seems I don't have such option. 
@Ardetus 
To do so, just close the PR and re-open it.
Info here:
https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit
Thx

**Comment by hugovk** [comment]
Is there no button like this at the top right?

image

https://travis-ci.org/dr-prodigy/python-holidays/builds/329627280

**Comment by dr-prodigy** [comment]
Okay, after a login on github the button appeared, so I restarted the build, but unfortunately, it's still failing.

**Comment by hugovk** [comment]
Great!

That looks like a temporary network error, restarting the individual job may help.

https://travis-ci.org/dr-prodigy/python-holidays/jobs/329627281

**Pull request merged**
