### PR TITLE
Spain sunday holidays to monday

### LINKED ISSUE #308: Spain Holidays that fall on Sunday are passed to Monday always
This year there are two days that fall on Sunday:

- 2020-11-01 Todos los Santos
- 2020-12-06 Día de la constitución Española

These days are not holidays. Right dates are:
- 2020-11-02 Todos los Santos
- 2020-12-07 Día de la constitución Española

More info in https://www.qppstudio.net/publicholidays2020/spain.htm

### PR DESCRIPTION
**Pull request by sermayoral**
This PR finalizes #310

Sorry @dr-prodigy, I were so busy in that date. I hope you are OK with this PR :-)

### CODE REVIEW

**Comment by sermayoral** [comment]
@dr-prodigy do you have five minutes for this? Past November 2nd was holiday (November 1st observed) and all my roller shutters went up as a working day 😅.

December 6th will ocurr again. I hope this will be fixed then 😊.

Thanks!!

**Comment by dr-prodigy** [comment]
Hey there @sermayoral 
thank you for your work, and sorry for my delay.

I've tried a merge of your work, but you have issues both with flake8 and coverage.
I would then kindly ask you to review and test your work using these instructions:
https://github.com/dr-prodigy/python-holidays#running-tests

Thank you very much, cheers! 👍 
dr-p

**Comment by sermayoral** [comment]
@dr-prodigy You are right! Sorry!

I'm fixing right now 👍 

Thank you!!

**Comment by dr-prodigy** [comment]
Brilliant.. thank you very much! 👍

**Pull request merged**
